Sistema web/config/routes.rb
Rails.application.routes.draw do

  scope module: 'api' do
    namespace :v1 do
      resources :patients, except: [:new, :edit]
      resources :sensors, except: [:new, :edit]
      resources :measures, except: [:new, :edit, :update]
    end
  end

  resources :patients
  resources :sensors, except: [:show]
  resources :measures, only: :destroy

  root "application#home"
end

Sistema web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Sistema web/app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :patient
  belongs_to :sensor

  validates :value, :patient, :sensor, presence: true

  def decrypted_value
    # El valor llega codificado en Base64
    decoded = Base64.decode64(self[:value])

    c = OpenSSL::Cipher::Cipher.new("aes-128-cbc")
    # Objeto de cifrado en modo para desencriptar
    c.decrypt
    # Importante, puesto que la información viene sin padding
    c.padding = 0
    # La clave y el vector de inicialización deben ser los mismos que los puestos al encriptar
    c.key = 'aaaabbbbccccdddd'
    c.iv = 'ABCDEFGHIJKLMNOP'
    d = c.update(decoded).unpack("A*").first.to_f

  end
end

Sistema web/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :measures

  validates :name, :email, presence: true
end

Sistema web/app/models/sensor.rb
class Sensor < ApplicationRecord
  has_many :measures, dependent: :destroy

  validates :name, :reads, presence: true
end

Sistema web/app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ActionController::API
    include ActionController::Serialization
  end
end

Sistema web/app/controllers/api/v1/measures_controller.rb
module Api::V1
  class MeasuresController < ApiController
    before_action :set_measure, only: [:show, :destroy]

    # GET /api/v1/measures
    def index
      render json: Measure.all.order(created_at: :desc)
    end

    # GET /api/v1/measures/:id
    def show
      render json: @measure
    end

    # POST /api/v1/measures
    def create
      measure = Measure.new(measure_params)
      if measure.save
        render json: measure, status: :ok
      else
        render json: measure.errors, status: :unprocessable_entity
      end
    end

    # DESTROY /api/v1/measures/:id
    def destroy
      render json: @measure.destroy
    end

    private

    def set_measure
      @measure = Measure.find params[:id]
    end

    def measure_params
      params.require(:measure).permit(:value, :sensor_id, :patient_id)
    end
  end
end

Sistema web/app/controllers/api/v1/patients_controller.rb
module Api::V1
  class PatientsController < ApiController
    before_action :set_patient, only: [:show, :update, :destroy]

    # GET /api/v1/patients
    def index
      render json: Patient.all.order(created_at: :desc)
    end

    # GET /api/v1/patients/:id
    def show
      render json: @patient
    end

    # POST /api/v1/patients
    def create
      patient = Patient.new(patient_params)
      if patient.save
        render json: patient, status: :ok
      else
        render json: patient.errors, status: :unprocessable_entity
      end
    end

    # PUT /api/v1/patients
    def update
      if @patient.update_attributes(patient_params)
        render json: @patient, status: :ok
      else
        render json: @patient.errors, status: :unprocessable_entity
      end
    end

    # DESTROY /api/v1/patients/:id
    def destroy
      render json: @patient.destroy
    end

    private

    def set_patient
      @patient = Patient.find params[:id]
    end

    def patient_params
      params.require(:patient).permit(:name, :description, :email, :phone)
    end
  end
end

Sistema web/app/controllers/api/v1/sensors_controller.rb
module Api::V1
  class SensorsController < ApiController
    before_action :set_sensor, only: [:show, :update, :destroy]

    # GET /api/v1/sensors
    def index
      render json: Sensor.all.order(created_at: :desc)
    end

    # GET /api/v1/sensors/:id
    def show
      render json: @sensor
    end

    # POST /api/v1/sensors
    def create
      sensor = Sensor.new(sensor_params)
      if sensor.save
        render json: sensor, status: :ok
      else
        render json: sensor.errors, status: :unprocessable_entity
      end
    end

    # PUT /api/v1/sensors
    def update
      if @sensor.update_attributes(sensor_params)
        render json: @sensor, status: :ok
      else
        render json: @sensor.errors, status: :unprocessable_entity
      end
    end

    # DESTROY /api/v1/sensors/:id
    def destroy
      render json: @sensor.destroy
    end

    private

    def set_sensor
      @sensor = Sensor.find params[:id]
    end

    def sensor_params
      params.require(:sensor).permit(:name, :reads, :description)
    end
  end
end

Sistema web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
    @measures_count = Measure.all.count
    @patients_count = Patient.joins(:measures).distinct.count
    @sensors_count = Sensor.all.count
  end
end

Sistema web/app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure
  def destroy
    if @measure.destroy
      redirect_to @measure.patient, notice: "La medición fue eliminada correctamente"
    else
      redirect_to @measure.patient, alert: "No se pudo eliminar la medición"
    end
  end

  private

  def set_measure
    @measure = Measure.find params[:id]
  end
end

Sistema web/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all.order(:created_at)
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient, notice: "El paciente fue creado correctamente"
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: "El paciente fue actualizado correctamente"
    else
      render :edit
    end
  end

  def destroy
    if @patient.destroy
      redirect_to patients_path, notice: "El paciente fue eliminado correctamente"
    else
      redirect_to @patient, alert: "No se pudo eliminar el paciente"
    end
  end

  private

  def set_patient
    @patient = Patient.find params[:id]
  end

  def patient_params
    params.require(:patient).permit(:name, :description, :email, :phone)
  end
end

Sistema web/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:edit, :update, :destroy]
  def index
    @sensors = Sensor.all.order(:created_at)
  end

  def new
    @sensor = Sensor.new
  end

  def edit
  end

  def create
    @sensor = Sensor.new(sensor_params)
    if @sensor.save
      redirect_to sensors_path, notice: "Sensor creado correctamente"
    else
      render :new
    end
  end

  def update
    if @sensor.update(sensor_params)
      redirect_to sensors_path, notice: "Sensor actualizado correctamente"
    else
      render :edit
    end
  end

  def destroy
    if @sensor.destroy!
      redirect_to sensors_path, notice: "Sensor eliminado correctamente"
    else
      redirect_to sensors_path, alert: "No se pudo eliminar el sensor #{@sensor.name} con ID #{@sensor.id}"
    end
  end

  private

  def sensor_params
    params.require(:sensor).permit(:name, :reads, :description)
  end

  def set_sensor
    @sensor = Sensor.find params[:id]
  end
end

Sistema web/app/helpers/application_helper.rb
module ApplicationHelper
end

Sistema web/app/helpers/measures_helper.rb
module MeasuresHelper
end

Sistema web/app/helpers/patients_helper.rb
module PatientsHelper
end

Sistema web/app/helpers/sensors_helper.rb
module SensorsHelper
end

Sistema web/app/views/application/_statistic_card.html.erb
<div class="card text-center">
  <% if defined? header %>
    <div class="card-header">
      <%= header %>
    </div>
  <% end %>
  <div class="card-body">
    <h1 class="card-title"><%= number || 0 %></h1>
    <p class="card-text"><%= description %></p>
    <% if defined? go_to %>
      <%= link_to go_to.name, go_to.path, class: "btn btn-outline-primary" %>
    <% end %>
  </div>
  <% if defined? footer %>
    <div class="card-footer text-muted">
      <%= footer %>
    </div>
  <% end %>
</div>

Sistema web/app/views/application/home.html.erb
<main class="home">
  <div class="jumbotron">
    <h1 class="display-3">Sistema de sensado de variables de salud por encriptación</h1>
    <p class="lead">Este sistema provee una interacción básica con el usuario encargado de administrar los pacientes y sensores que se disponen. A su vez provee de una API para poder ser usada por los dispositivos lectores de datos.</p>
    <hr class="my-4">
    <p class="no-margin">Para ver más sobre la documentación de este sistema visitar <%= link_to "el proyecto en Github", "https://github.com/juanmanuelramallo/TDPII-sistema-de-salud/blob/master/README.md" %></p>
  </div>
  <hr class="my-4">
  <div class="row">
    <div class="col-md-4">
      <%= render "statistic_card", number: @measures_count, description: "Cantidad total de mediciones tomadas" %>
    </div>
    <div class="col-md-4">
      <%= render "statistic_card", number: @patients_count, description: "Cantidad total de pacientes atendidos" %>
    </div>
    <div class="col-md-4">
      <%= render "statistic_card", number: @sensors_count, description: "Cantidad de sensores en funcionamiento" %>
    </div>
  </div>
</main>

Sistema web/app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

Sistema web/app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <%= link_to "Sistema de salud", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Inicio", root_path, class: "nav-item nav-link" %>
      <%= link_to "Pacientes", patients_path, class: "nav-item nav-link" %>
      <%= link_to "Sensores", sensors_path, class: "nav-item nav-link" %>
    </div>
  </div>
</nav>

Sistema web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaDeSalud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <main class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

Sistema web/app/views/patients/_form.html.erb
<%= simple_form_for @patient do |f|%>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :description, as: :text %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

Sistema web/app/views/patients/edit.html.erb
<main class="patients-edit">
  <h2>Etidando Paciente - <%= @patient.name %></h2>
  <%= render "form" %>
</main>

Sistema web/app/views/patients/index.html.erb
<main class="patients-index">
  <div class="row">
    <div class="col-md-8">
      <h1>Listado de Pacientes</h1>
    </div>

    <div class="col-md-4 text-right">
      <%= link_to "Añadir", new_patient_path, class: "btn btn-outline-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% if @patients.any? %>
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Email</th>
              <th>Teléfono</th>
              <th>Descripción</th>
              <th>Creado el día</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @patients.each do |patient| %>
              <tr>
                <td><%= patient.id %></td>
                <td><%= patient.name %></td>
                <td><%= patient.email %></td>
                <td><%= patient.phone %></td>
                <td><%= patient.description %></td>
                <td><%= l patient.created_at, format: :short %></td>
                <td><%= link_to "Ver", patient %> | <%= link_to "Editar", edit_patient_path(patient) %> | <%= link_to "Eliminar", patient, method: :delete, data: { confirm: "¿Estás seguro que deseas eliminar este paciente?" } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="alert alert-info">
          No hay pacientes para mostrar
        </div>
      <% end %>
    </div>
  </div>
</main>

Sistema web/app/views/patients/new.html.erb
<main class="patients-new">
  <h2>Nuevo Paciente</h2>

  <%= render "form" %>
</main>

Sistema web/app/views/patients/show.html.erb
<main class="patients-show">
  <h1>Paciente #<%= "#{@patient.id} | #{@patient.name}" %></h1>
  <div class="row">
    <div class="col-md-8">
      <h2>Mediciones</h2>
    </div>
    <div class="col-md-4 text-right">
      <%= link_to "Editar", edit_patient_path(@patient), class: "btn btn-outline-secondary" %>
      <%= link_to "Eliminar", @patient, method: :delete, data: { confirm: "¿Estás seguro que deseas eliminar este paciente?" }, class: "btn btn-outline-danger" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <% if @patient.measures.any? %>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Valor</th>
              <th>Sensor</th>
              <th>Realizado el</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @patient.measures.order(created_at: :desc).each_with_index do |measure, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= measure.value %> <br> <%= measure.decrypted_value %></td>
                <td><%= measure.sensor.name %></td>
                <td><%= l measure.created_at, format: :short %></td>
                <td><%= link_to "Eliminar", measure, method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="alert alert-info">
          No hay mediciones para mostrar
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          Datos del paciente
        </div>
        <ul class="list-group">
          <li class="list-group-item">ID: <%= @patient.id %></li>
          <li class="list-group-item">Nombre: <%= @patient.name %></li>
          <li class="list-group-item">Email: <%= @patient.email %></li>
          <li class="list-group-item">Teléfono: <%= @patient.phone %></li>
          <li class="list-group-item">Descripción: <%= @patient.description %></li>
          <li class="list-group-item">Creado el <%= l @patient.created_at, format: :long %></li>
          <li class="list-group-item">Mediciones: <%= @patient.measures.count %></li>
          <li class="list-group-item">Última medición: <%= @patient.measures.order(:created_at).last.try { |m| m.created_at.to_s :long } || '-' %></li>
        </ul>
      </div>
    </div>
  </div>
</main>

Sistema web/app/views/sensors/_form.html.erb
<%= simple_form_for @sensor do |f| %>
  <%= f.input :name %>
  <%= f.input :reads %>
  <%= f.input :description, as: :text %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

Sistema web/app/views/sensors/edit.html.erb
<main class="sensors-edit">
  <h2>Editando Sensor #<%= "#{@sensor.id} #{@sensor.name}" %></h2>

  <%= render "form" %>
</main>

Sistema web/app/views/sensors/index.html.erb
<main class="sensors-index">
  <div class="row">
    <div class="col-md-8">
      <h2>Sensores</h2>
    </div>
    <div class="col-md-4 text-right">
      <%= link_to "Añadir", new_sensor_path, class: "btn btn-outline-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% if @sensors.any? %>
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Lee</th>
              <th>Descripción</th>
              <th>Lecturas tomadas</th>
              <th>Creado el día</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @sensors.each do |sensor| %>
              <tr>
                <td><%= sensor.id %></td>
                <td><%= sensor.name %></td>
                <td><%= sensor.reads %></td>
                <td><%= sensor.description %></td>
                <td><%= sensor.measures.count %></td>
                <td><%= sensor.created_at.to_s :short %></td>
                <td><%= link_to "Editar", edit_sensor_path(sensor) %> | <%= link_to "Eliminar", sensor, method: :delete, data: { confirm: "¿Estás seguro que deseas eliminar el sensor #{sensor.name} con ID #{sensor.id}?" } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="alert alert-info">
          No hay sensores para mostrar.
        </div>
      <% end %>
    </div>
  </div>

</main>

Sistema web/app/views/sensors/new.html.erb
<main class="sensors-new">
  <h2>Nuevo Sensor</h2>

  <%= render "form" %>
</main>